### PR TITLE
Feature/sap 3.0

### PR DESCRIPTION
**Pull request by DickKnol**
Here's a pull request for getting a connection to SAP through RFC using the pyRFC library. The code is "borrowed" from the Outgoing Odoo connection.

### CODE REVIEW

**Comment by DickKnol** [comment]
#385

**Comment by DickKnol** [comment]
Hi @dsuch,

I've been testing with Vegeta to load test the environment. Here are the results of performing a zato ping for 30 seconds @ 500 req/s:
```
zato@srvzato01:~$ echo "GET http://localhost:11223/zato/ping" | ./vegeta attack -duration=30s -rate=500 | tee results.bin | ./vegeta report
Requests      [total, rate]            15000, 500.03
Duration      [total, attack, wait]    39.956278817s, 29.99799984s, 9.958278977s
Latencies     [mean, 50, 95, 99, max]  1.046879945s, 293.940514ms, 7.115522586s, 15.145425716s, 30.000387893s
Bytes In      [total, mean]            1737190, 115.81
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  92.31%
Status Codes  [code:count]             0:1084  504:70  200:13846
Error Set:
Get http://localhost:11223/zato/ping: dial tcp 0.0.0.0:0->127.0.0.1:11223: socket: too many open files
504 Gateway Time-out
Get http://localhost:11223/zato/ping: dial tcp 0.0.0.0:0->[::1]:11223: getsockopt: connection refused
zato@srvzato01:~$ 
```

In the mean time starting a service to get data from SAP. There is a pool of 3 connections to SAP. Test performed for 10 seconds @ 100 reqs/s:
```
zato@srvzato01:~$ echo "GET http://localhost:11223/sap-ping" | ./vegeta attack -duration=10s -rate=100 | tee results.bin | ./vegeta report
Requests      [total, rate]            1000, 100.10
Duration      [total, attack, wait]    23.751100067s, 9.989999913s, 13.761100154s
Latencies     [mean, 50, 95, 99, max]  3.031611083s, 1.44884799s, 15.046243441s, 15.514346691s, 15.662089684s
Bytes In      [total, mean]            1149160, 1149.16
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  98.80%
Status Codes  [code:count]             200:988  504:12
Error Set:
504 Gateway Time-out
zato@srvzato01:~$
```
There are only a few gateway timeouts for SAP connections, or are you also worried about the connections refused for the zato ping?

Increasing the time to 1 minute gives more errors, but the connection to SAP remains and is stable.

Here's the simple sap ping service:
```python
class Ping(Service):
    class SimpleIO(object):
        response_elem = 'companies'

    def handle(self):
        params = {"query": "select * from T001 WHERE BUKRS = '0001'"}

        statuses = self.invoke('sap.readtable.sql', params, as_bunch=True)

        self.response.payload = dumps(statuses)

```

**Comment by dsuch** [comment]
OK, thanks but I'm just wondering why it is not 100%? What is in server.log files when there are errors?

**Comment by DickKnol** [comment]
The errors were mainly due to that I had only one server running. After starting two servers, with pool size 1 I get the following results (100% correct, in total 600 reqs/s).

Running for three minutes with 100% score.
```
zato@srvzato01:~$ echo "GET http://localhost:11223/zato/ping" | ./vegeta attack -duration=180s -rate=500 | tee results.bin | ./vegeta report
Requests      [total, rate]            90000, 500.01
Duration      [total, attack, wait]    3m0.002546348s, 2m59.997999859s, 4.546489ms
Latencies     [mean, 50, 95, 99, max]  173.183597ms, 47.672248ms, 677.662471ms, 1.187673908s, 4.112602336s
Bytes In      [total, mean]            11250000, 125.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:90000
Error Set:
zato@srvzato01:~$
```
Starting after a few seconds and running for 170 seconds with 100% score.
```
zato@srvzato01:~$ echo "GET http://localhost:11223/sap-ping" | ./vegeta attack -duration=170s -rate=100 | tee results.bin | ./vegeta report
Requests      [total, rate]            17000, 100.01
Duration      [total, attack, wait]    2m50.094638754s, 2m49.989999907s, 104.638847ms
Latencies     [mean, 50, 95, 99, max]  342.798298ms, 163.143716ms, 1.214344261s, 1.646578542s, 4.332066693s
Bytes In      [total, mean]            19754000, 1162.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:17000
Error Set:
zato@srvzato01:~$
```

**Comment by dsuch** [comment]
Thanks, I will be merging it to a separate branch in the main repository to investigate the licensing side too.

According to the driver's [readme](https://github.com/SAP/PyRFC), one needs to open a SAP Service Marketplace account as a prerequisite so we cannot just distribute it along with other dependencies, there will have to be some instructions on how to enable the feature manually, similar to what we have today for Oracle DB or IBM MQ:

https://zato.io/docs/3.0/admin/guide/enabling-extra-libs.html

**Comment by dsuch** [comment]
Hi @DickKnol - many thanks for this feature! I have just merged it in.

About the only thing that I changed is that I made it all optional - the installation of PyRFC requires a customer or partner account on SAP Service Marketplace so there cannot be a link to in requirements.txt. 

Instead, I will add a note to documentation about where to find this library and that it needs to be installed first before SAP connections can be used.

Regards.

**Pull request merged**
