### PR TITLE
Bugfix for pinging Odoo

### PR DESCRIPTION
**Pull request by DickKnol**
Odoo connector ping fix

### CODE REVIEW

**Comment by jpoa** [comment]
Greetings!

I have only ran this against a v10 but the fix makes sense to me based on the library and I can confirm the fix works.

Not wanting to hijack the thread, but can anyone give some specifics as to why this particular library was chosen for the Odoo integration?

**Comment by dsuch** [comment]
Thanks for the confirmation @jpoa!

This library was chosen because at the time of its inception it was the official library for OpenERP, later renamed to Odoo.

Do you suggest to have a look at a different one?

Regards.

**Comment by jpoa** [comment]
@dsuch perhaps yes.

I have used three libraries so far, with different degrees of experience, in order:

* [erppeek](https://github.com/tinyerp/erppeek)
* [openerp-client-lib](https://pypi.org/project/openerp-client-lib/)
* [openerp-proxy](https://github.com/katyukha/openerp-proxy/tree/master)

As you have stated, openerp-client-lib was a very common one, but its a bit too cryptic to use if you ask me. ERPPeek is more pythonic and in more than two years with heavy use I have yet to find any trouble with it. The last one, openerp-proxy, has nice integrations with Jupyter and the extension mechanism they implement brings quite some simplification to its use.

I am a bit proponent of simplified syntax, but not at the cost of stability.

openerp-proxy claims some improvements also in terms of performance, I wanted to do an analysis of the three libraries and get some factual evaluation. From what I have seen, changing the library in Zato would not be a big hassle (code-wise), the issue in the end is related to the existing user code base that would have to be migrated.

It was with this in mind that I asked why was the openerp-client-lib chosen, perhaps there was something else that I missed.

One concern in my eyes that would justify some thought is the fact that openerp-client-lib seems to be somewhat stalled, ie, I have not even tested it with V11 or the current master.

Would it be interesting to pursue the aforementioned analysis and get back here with findings?

**Comment by dsuch** [comment]
Thanks @jpoa - it's good to hear about the alternatives, I opened a dedicated ticket for it, here it is #848.

**Pull request merged**
