### PR TITLE
FTPS support

### PR DESCRIPTION
**Pull request by DickKnol**
This pull request adds support for FTPS to Zato

### CODE REVIEW

**Comment by samrose** [comment]
(not a criticism, just curious) why FTP_TLS over http://docs.paramiko.org/en/2.1/api/sftp.html ?

**Comment by DickKnol** [comment]
Because I need to connect to a Windows FTP server which uses TLS (see https://www.iis.net/configreference/system.applicationhost/sites/site/ftpserver/security/ssl), which is not the same as SFTP (file operations over SSH)

**Comment by dsuch** [comment]
Hi @DickKnol,

this is good stuff, I hope it wasn't too difficult to get acquainted with the custom frontend framework on top of Django that we have in web-admin.

One question - were you testing it on Ubuntu or Debian?

Thanks.

**Comment by DickKnol** [comment]
I've tested this on Ubuntu 16.04.02 LTS. I was just following the dircache field, which was quite similar.

**Comment by dsuch** [comment]
Perfect, thanks a lot!

**Pull request merged**
