### PR TITLE
GH #1037 ibm mq reconnect cycle for mq error 2161,2538,2009

### PR DESCRIPTION
**Pull request by fenist19**
#1037

### CODE REVIEW

**Comment by dsuch** [comment]
Thanks, I will check it as soon as possible.

**Comment by fenist19** [comment]
Hello. Will you check this merge?

**Comment by dsuch** [comment]
Hello @fenist19 - yes, I will. Unfortunately, due to other commitments, I do not have time to do it currently.

**Comment by dsuch** [comment]
This is merged - can you try it out, please?

**Comment by fenist19** [comment]
It works. thanks.

**Pull request merged**
