### PR TITLE
Synchronous AMQP channel + SOAP blocking pool

### PR DESCRIPTION
**Pull request by lucval**
Hello,

I've taken the time to implement a synchronous AMQP channel for Zato.

A new boolean field 'is_sync" is added to the AMQP channel structure. When active, the channel will invoke the on-consume service before sending an ACK to the queue. If the invoked service does not reply with a 200 OK, the message will be rejected via a NACK with the requeue flag set. The "nack_timeout" attribute can be used to specify the amount of seconds that the consuming process will wait (sleep) after nacking a message to avoid nasty queue loops.
"prefetch_count" is the last paramater added to the channel AMQP structure. This is used to limit the amount of standing unacknowledged messages while consuming. For async AMQP channel, the "prefetch_count" will not be set since all messages are acknowledged prior to their consumption.

As a bonus I've also enhanced the AMQP channel to re-establish connections when lost or simply shutdown from the server. Dropped connections are detected by pika both on a connection and on a channel level. Proper callbacks are implemented to handle both scenarios.

Now everything looks in order and works fine but one thing emerged in this first week of usage: Zato is quite slow in consuming the messages. This is clearly due to the fact that for synchronously consuming the messages, the Util module (from zato cli) has been used. This module, as you know, invokes services via the /zato/admin/invoke API introducing thus useless HTTP overhead. Unfortunately I was unable to find/implement (importing ParallelServer resulted in a failure) any other more suited approaches to solve this issue and therefore I pose the question to you. If you could shed some lights, I will then update this branch with the proposed solution.

Regards
Luca

### CODE REVIEW

**Comment by dsuch** [comment]
Hi @lucval - this is a great contribution and I'll need a moment to go through it all.

Another point, partly related to what you have raised, is that in one of the next micro releases (2.0.8-2.0.9) and I'd like to do away with dedicated AMQP connectors.

It was a good idea in its own time when there were no greenlet-safe AMQP libraries but now all of it can be moved to the core ParallelServer without IPC through Redis.

This will increase robustness of the whole solution + will help make servers consume messages off queues faster.

What do you think?

**Comment by lucval** [comment]
I definitely see the need of having the opportunity to define both synchronous and asynchronous AMQP channel. In my personal experience we use MQ to exchange CDRs, which given the customer base can become quite a big amount of traffic. Therefore the 2 main features that the queue consumer should have are:
- speed in processing the messages
- and capability to re-queue messages which failed to be processed (and for which a re-consumption should end in a success).

Both these features can only be achieved if the queue is consumed in a synchronous manner.

As I already said, I've been trying to develop message consumption via a Parallel Server instance which I would have retrieved in the garbage collector (ugly). I then soon discover that instantiating a Parallel Server in the server.connection module was not as easy as I thought and therefore decided for the easier but even uglier solution that I've proposed.

**Comment by lucval** [comment]
As already mentioned, I have pushed a new commit which implements a blocking pool for outgoing SOAP channels.

While implementing this I had a closer look at Zato internal pooling system and honestly did not understand why a second (more external) pool has been implemented. In my opinion everything could be handled by python's requests pool alone with no need to add an extra queueing.
Furthermore I have managed to come around the first pooling system by simply allocating the connection.client entity and assign it to the invoking service class. At this point the Zato connection entity can be released right away but the actual HTTP/SOAP connection can still be used. Other services can do the same, creating a situation where one Zato connection can be shared among N workers while the actual pooling is handled by the requests module. This increased even more the doubt over the need of a Zato's own connection pool wrapped around the actual HTTP connection pool...

**Comment by dsuch** [comment]
Hi @lucval - which internal pool are you thinking of? Which of the pools in the requests package could replace it in which Zato module exactly?

Thanks.

**Comment by lucval** [comment]
Hi @dsuch,
the internal pool (which I referred to as the most external of the two) is implemented in zato-server's connection.queue by mean of a gevent queue of connection.client objects. The other pool is (rightly so) implemented in the requests module session by the BaseHTTPSOAPWrapper object.

**Comment by dsuch** [comment]
Thanks @lucval but I'm still unclear which the other one is, the one that is related to the requests module. Can you please link me to a source line on GH where you can see it's used? I'm just not clear if it's not the same one from ```zato.server.connection.queue```?

Note that the ```zato.server.connection.queue``` one is used in OpenStack Swift, S3 or Solr and will be used more in the future with Python dependencies that are not thread (greenlet) safe but I'm just not clear on the HTTP part you're thinking of.

Right now it's used by suds-based SOAP outgoing connections, that's correct. The reason is that suds objects cannot be shared by threads (greenlets). But I'm not sure if this is the thing you mean?

Thanks again.

**Pull request closed without merging**
