### PR TITLE
MS SQL support, Docker container, improved KVDB and from_config password fix

### PR DESCRIPTION
**Pull request by akotulu**
Tested pymssql with this service. Added 3 10s intervalled scheduled tasks and UI stayed responsive as it should. Before adding wait_callback, single service locked UI. 

```
from zato.server.service import Service
from contextlib import closing
from sqlalchemy import text

class MSSQLTest(Service):

  def handle(self):
    """Service entry point
    """
    self.logger.info('fetching mssql')

    with closing(self.outgoing.sql.get('mssqltest').session()) as session:
      result = session.execute(text("WAITFOR DELAY '00:00:10'"))
      result = session.execute(text("SELECT 1"))
      self.logger.info(result)
```

### CODE REVIEW

**Comment by dsuch** [comment]
Hello @akotulu,

by sheer coincidence, I spoke about MS SQL with users who were using pymssql with Zato and discouraged me from basing our support for MS SQL on that library - the reason were data losses in actual environments.

I cannot confirm it personally because that was done outside of core Zato but it did not sound very good and I decided to base MS SQL support on [mxODBC Connect](https://www.egenix.com/products/python/mxODBCConnect) instead of pymssql, because mxODBC Connect explicitly lists support for gevent.

That said, I think I will try to make support for databases configurable in server.conf instead of Python code which means that one will be still able to use pymssql for MS SQL or other libraries for different databases.

Not having used pymssql extensively, I am reluctant to make it a library core to our needs but if there were config files for SQL driver configuration, this would satisfy needs of people who wanted to use this library or different ones.

PS. I haven't yet looked at the other changes that you sent in - I am thankful for it all and will be sure to do it.

Regards.

**Comment by akotulu** [comment]
No problems, as we use pymssql in banking software and have never encountered any problems with this library, I can't confirm any data losses. Someone has been brainwashed with falsified information to suppress usage of freetds. Corporate shills have a impact on things people think, so be careful what you trust these days. About freetds, microsoft wants to get ridd of it, cause maker reverse engineered whole MS SQL protocol and its faster than odbc.

**Comment by dsuch** [comment]
I will add your changes to 3.0 but this PR I will need to reject because I do not want to merge pymssql changes (there is now functionality of SQL plugins since #806) and I want to change commit messages. I will see how to cherrypick concrete commits from your fork. Thanks.

**Comment by akotulu** [comment]
Ok, take what you need. Just to add, fork went live last week at the company I needed these changes. Time tells if pymssql is as bad as they say. All other releases are working as expected which I have developed in the past for 7 years for them with pymssql (including transaction proxies).

SQL support as plugins is better solution anyway. Just a note, many companies are using mssql as their main database engine and not having it in base build is kinda rejecting, but in other hand removing Microsoft from open source is a good take on things, as they are evil, secretly stealing all the mayor companies trade secrets and selling it, including personal data with W10, which is a keylogger if you get the drift).

Anyway, best of time, I'll be keeping eye on things, hope to be helpful in the future. I have suggested your hard work for as many guys I know, I'm sure they will be picking it up in the near future!

**Comment by dsuch** [comment]
@akotulu - I am thankful for your engineering contributions but this is not your personal blogging space. I do not want any such comments anymore.

**Pull request closed without merging**
