### PR TITLE
Fixes for file pickup python3

### PR DESCRIPTION
**Pull request by DickKnol**

### CODE REVIEW

**Comment by dsuch** [comment]
Hi @DickKnol - thanks, this looks good on the face of it but I am not sure, why were the changes to pickup required?

**Comment by DickKnol** [comment]
Hi @dsuch 
I have another service (non-zato) that puts a file on the zato server. It will create a temporary file first, then rename/move it. Sometimes the rename/move was detected by zato, if the file was put there quickly enough, but sometimes the file was first detected, not within file filter (*.xml) and then renamed to .xml. The rename was not triggering the pickup.

**Comment by dsuch** [comment]
Thanks, I am merging it in.

**Comment by dsuch** [comment]
Hi @DickKnol - I merged it but then I realised that it was based on `support/3.1`. Would it be please possible for you to send it to branch `main` instead? We are close to the new release and I would rather not push anything new to support/3.1. Thanks.

**Pull request merged**
